services:
  app:
    build: .
    environment:
      DEVICE_API_KEY: ${DEVICE_API_KEY:-}
      DEVICE_API_KEY_DEV_BLN: ${DEVICE_API_KEY_DEV_BLN:-}
      DEVICE_API_KEY_MONA_DEV_001: ${DEVICE_API_KEY_MONA_DEV_001:-}
      DEVICE_API_KEY_MONA_DEVICE_ID_001: ${DEVICE_API_KEY_MONA_DEVICE_ID_001:-}
    volumes:
      - .:/app
    ports:
      - 8024:8024
      - 9024:9024
      - 8080:8080

volumes:
  app-python-site-packages:
    driver: local
  app-usr-local-bin:
    driver: local
