version: "3"
services:
  app:
    build: .
    volumes:
      - .:/app
      - app-python-site-packages:/usr/local/lib/python3.6
      - app-usr-local-bin:/usr/local/bin
    command: "tail -f /dev/null"
    working_dir: /app
    ports:
      - 8024:8024

volumes:
  app-python-site-packages:
    driver: local
  app-usr-local-bin:
    driver: local
